export const activities = [
  {
    id: 0,
    name: "DIA A DIA",
    src: "00_dia_a_dia.png",
    type: "LEVE",
  },
  {
    id: 1,
    name: "CAMINHADA",
    src: "01_caminhada.png",
    type: "LEVE",
  },
  {
    id: 2,
    name: "YOGA",
    src: "02_yoga.png",
    type: "LEVE",
  },
  {
    id: 3,
    name: "PILATES",
    src: "03_pilates.png",
    type: "LEVE",
  },
  {
    id: 4,
    name: "BALLET",
    src: "04_ballet.png",
    type: "LEVE",
  },
  {
    id: 5,
    name: "TRILHA",
    src: "05_trilha.png",
    type: "LEVE",
  },
  {
    id: 6,
    name: "MUSCULAÇÃO",
    src: "06_musculacao.png",
    type: "MÉDIO",
  },
  {
    id: 7,
    name: "GINASTICA",
    src: "07_ginastica.png",
    type: "MÉDIO",
  },
  {
    id: 8,
    name: "TÊNIS",
    src: "08_tenis.png",
    type: "MÉDIO",
  },
  {
    id: 9,
    name: "DANÇA",
    src: "09_danca.png",
    type: "MÉDIO",
  },
  {
    id: 10,
    name: "CICLISMO",
    src: "10_ciclismo.png",
    type: "MÉDIO",
  },
  {
    id: 11,
    name: "VOLÊI",
    src: "11_volei.png",
    type: "MÉDIO",
  },
  {
    id: 12,
    name: "CORRIDA",
    src: "12_corrida.png",
    type: "ALTO",
  },
  {
    id: 13,
    name: "BOXE",
    src: "13_boxe.png",
    type: "ALTO",
  },
  {
    id: 14,
    name: "FUTEBOL",
    src: "14_futebol.png",
    type: "ALTO",
  },
  {
    id: 15,
    name: "BASQUETE",
    src: "15_basquete.png",
    type: "ALTO",
  },
  {
    id: 16,
    name: "INTENSO",
    src: "16_intenso.png",
    type: "ALTO",
  },
  {
    id: 17,
    name: "HIIT",
    src: "17_hiit.png",
    type: "ALTO",
  },
];
